# Generated by Django 3.0.3 on 2020-02-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('work', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('duration', models.DurationField()),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField()),
                ('timer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TimerType')),
            ],
        ),
    ]
