# Generated by Django 3.0.3 on 2020-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200208_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='end',
        ),
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
